# 沙箱与被测仓身份。在任何环境变量之后钉死，不能改写成 g-lite/consumer。

HARNESS_SUT_REPO="qiaoen12/g-lite"
HARNESS_SUT_MAIN="main"
HARNESS_SANDBOX_REPO="qiaoen12/g-lite-harness"
HARNESS_SANDBOX_MAIN="e2e/base"
HARNESS_E2E_PREFIX="e2e/"

# 兼容现有 e2e 脚本使用的变量名。
SUT_REPO="$HARNESS_SUT_REPO"
SUT_MAIN="$HARNESS_SUT_MAIN"
SANDBOX_REPO="$HARNESS_SANDBOX_REPO"
SANDBOX_MAIN="$HARNESS_SANDBOX_MAIN"
E2E_BRANCH_PREFIX="$HARNESS_E2E_PREFIX"
